DEBUG = 'DEBUG'
PRODUCTION = 'PRODUCTION'

ENV = PRODUCTION
PREFILL_AUDIO = True
USE_EXAMPLE = True
DO_FOLLOW_EXAMPLE_AS_SCRIPT = False

SCRIPT_TIME_RATIO = 1
USE_TELEPROMPT = True
TELEPROMPT_IP = '192.168.137.193'
# TELEPROMPT_IP = 'localhost'

# NOISE_THRESHOLD = -10.6   # headset at lab 1
# NOISE_THRESHOLD = -8.8      # lab 3
NOISE_THRESHOLD = -7.4      # Teo new room
PAUSE_N_PAGES_THRESHOLD = 40.0
